channels:
- conda-forge
dependencies:
- python=3.11.10
- pip<=24.2
- pip:
  - mlflow==2.11.4
  - cloudpickle==3.0.0
  - psutil==5.9.0
  - scikit-learn==1.3.0
  - typing-extensions==4.15.0
name: mlflow-env
